# Display.
title: "Merely Useful"
subtitle: "A Pragmatic Introduction to Research Computing"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/gvwilson/merely-useful/"
email: "gvwilson@third-bit.com"
isbn: "000-0-0000000-0"
website: "https://gvwilson.github.io/merely-useful/"
purchase: ""
paypal: ""

# Theme color.
background: "#f0e0e0"

# Jekyll settings.
highlighter: rouge
plugins:
  - "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- requirements.txt
- tex_en/inc

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_en
    values:
      language: "en"
      layout: "default"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /tidy/
  - /r/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /gloss/

# Translations by language.
translations:
  en:
    generated: "Last generated"
    objectives: "After reading this chapter, you will be able to..."
    singlepage: "Single page version"
