# Display.
title: "Merely Useful"
subtitle: "A Pragmatic Introduction to Research Computing"
author: "Greg Wilson"
copyrightyear: "2018"

# Code highlighting.
highlighter: rouge

# GitHub repository.
repository: gvwilson/merely-useful/

# Pages that are stored in the root directory by convention.
# Since they aren't part of a collection, their titles have
# to be stored here explicitly.
toplevel:
- permalink: /license/
  title: "License"
- permalink: /conduct/
  title: "Code of Conduct"

# Collections: one for lessons, one for extras.
collections:
  lessons:
    output: true
  extras:
    output: true

# Order for lessons.
lessons:
- /intro/

# Order for extras.
extras:
- /reference/
- /gloss/
- /bib/
