# Display.
title: "FIXME"
subtitle: "FIXME"
author: "FIXME"
copyrightyear: "2018"
repo: https://github.com/gvwilson/youbou/
email: fixme@fixme.org
isbn: "000-0-0000000-0"
website: FIXME

# Theme color.
background: "#f0f0e0"

# Code highlighting.
highlighter: rouge

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- requirements.txt
- tex_um/inc

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_um:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_um
    values:
      language: "um"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /conclusion/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /bib/
  - /gloss/

# Translations by language.
translations:
  um:
    generated: "Lastum generatum"
    objectives: "Sodales ut etiam sit amet nisl purus in..."
