# Display.
title: "FIXME"
subtitle: "FIXME"
author: "FIXME"
copyrightyear: "2018"
repo: https://github.com/gvwilson/FIXME/
email: FIXME@fixme.com

# Code highlighting.
highlighter: rouge

# Pages that are stored in the root directory by convention.
# Since they aren't part of a collection, their titles have
# to be stored here explicitly.
toplevel:
- permalink: /license/
  title: "License"
- permalink: /conduct/
  title: "Code of Conduct"

# Collections: one for lessons, one for extras.
collections:
  lessons:
    output: true
  extras:
    output: true

# Order for Table of Contents.
toc:
  toplevel:
  - /license/
  - /conduct/
  lessons:
  - /intro/
  extras:
  - /bib/
  - /gloss/
  - /reference/
